services:
  web-server:
    image: nginx:latest
    container_name: mi-servidor-nginx
    ports:
      - "80:80"
      - "8080:80"
      - "8443:443"
    volumes:
      - web_data:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - sftp-server

  sftp-server:
    image: atmoz/sftp
    container_name: mi-servidor-sftp
    ports:
      - "2222:22"
    volumes:
      - web_data:/home/usuario/upload
    command: usuario:1234:1001

volumes:
  web_data: